openapi: 3.0.0
info:
  title: HolidaysApp API Rest
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: organizations
    description: Get all organizations of Organizations APIs
paths:
  /api-rest/organizations:
    get:
      tags:
        - organizations
      summary: Get all organizations
      description: Get all organizations of Organizations APIs
      operationId: getAllOrganizations
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '500':
          description: Internal Server Error
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
components:
  schemas:
    AbstractJsonSchemaPropertyObject:
      type: object
      properties:
        title:
          type: string
        readOnly:
          type: boolean
    Item:
      type: object
      properties:
        type:
          type: string
        properties:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AbstractJsonSchemaPropertyObject'
        requiredProperties:
          type: array
          items:
            type: string
    JsonSchema:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        properties:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/AbstractJsonSchemaPropertyObject'
        requiredProperties:
          type: array
          items:
            type: string
        definitions:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Item'
        type:
          type: string
        $schema:
          type: string
    RepresentationModelObject:
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/Links'
    EntityModelOrganizationMO:
      type: object
      properties:
        name:
          type: string
        _links:
          $ref: '#/components/schemas/Links'
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    PagedModelEntityModelOrganizationMO:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            organizationMOes:
              type: array
              items:
                $ref: '#/components/schemas/EntityModelOrganizationMO'
        _links:
          $ref: '#/components/schemas/Links'
        page:
          $ref: '#/components/schemas/PageMetadata'
    OrganizationMORequestBody:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    Organization:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
    Links:
      type: object
      additionalProperties: true