CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER');

CREATE TYPE marital_status AS ENUM ('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'SEPARATED', 'PARTNERED' );

CREATE TYPE project_state AS ENUM ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

CREATE TYPE project_type AS ENUM ('INTERNAL', 'CLIENT', 'TRAINING');

CREATE TYPE roles AS ENUM ('ADMIN', 'USER', 'GUEST');

CREATE TYPE title AS ENUM ('SR', 'SRA', 'DR', 'DRA');

CREATE TYPE vacation_state AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TYPE vacation_type AS ENUM ('LOCAL_OR_NATIONAL_HOLIDAY', 'VACATION', 'LEAVE');